use crate::types::{Encoding, FoundString, Result};

use super::OutputMetadata;
use std::collections::{BTreeMap, HashMap};
use std::time::{SystemTime, UNIX_EPOCH};

/// Format strings as YARA rule templates.
pub fn format_yara(_strings: &[FoundString], _metadata: &OutputMetadata) -> Result<String> {
    let timestamp = _metadata
        .generated_at
        .clone()
        .unwrap_or_else(current_timestamp);
    let base_rule_name = sanitize_rule_name(&_metadata.binary_name);
    let rule_name = format!("{}_strings", base_rule_name);

    let mut output = String::new();
    output.push_str("// YARA rule generated by Stringy\n");
    output.push_str(&format!("// Binary: {}\n", _metadata.binary_name));
    output.push_str(&format!("// Generated: {}\n\n", timestamp));

    output.push_str(&format!("rule {} {{\n", rule_name));
    output.push_str("  meta:\n");
    output.push_str(&format!(
        "    description = \"Strings extracted from {}\"\n",
        escape_yara_string(&_metadata.binary_name)
    ));
    output.push_str("    generated_by = \"stringy\"\n");
    output.push_str(&format!("    generated_at = \"{}\"\n", timestamp));

    if _strings.is_empty() {
        output.push_str("  condition:\n");
        output.push_str("    true\n");
        output.push_str("}\n");
        return Ok(output);
    }

    let grouped = group_strings_by_tag(_strings);
    let mut strings_block = String::new();
    let mut counters: HashMap<String, usize> = HashMap::new();
    let mut included = 0usize;

    strings_block.push_str("  strings:\n");
    for (tag, items) in grouped {
        strings_block.push_str(&format!("    // tag: {}\n", tag));
        let var_tag = sanitize_identifier(&tag);
        for item in items {
            let char_count = item.text.chars().count();
            if char_count > 200 {
                strings_block.push_str(&format!(
                    "    // skipped (length > 200 chars): {}\n",
                    char_count
                ));
                continue;
            }

            let counter = counters.entry(var_tag.clone()).or_insert(0);
            *counter += 1;
            let var_name = format!("${}_{}", var_tag, *counter);
            strings_block.push_str(&format!("    // score: {}\n", item.score));

            match item.encoding {
                Encoding::Utf16Be => {
                    let hex = utf16be_hex_string(&item.text);
                    strings_block.push_str(&format!("    {} = {}\n", var_name, hex));
                }
                Encoding::Utf16Le => {
                    let escaped = escape_yara_unicode_literal(&item.text);
                    strings_block.push_str(&format!("    {} = \"{}\" wide\n", var_name, escaped));
                }
                Encoding::Ascii | Encoding::Utf8 => {
                    let escaped = escape_yara_string(&item.text);
                    let modifier = get_yara_modifier(item.encoding);
                    strings_block.push_str(&format!(
                        "    {} = \"{}\" {}\n",
                        var_name, escaped, modifier
                    ));
                }
            }
            included += 1;
        }
    }

    output.push_str(&strings_block);
    output.push_str("  condition:\n");
    if included == 0 {
        output.push_str("    true\n");
    } else {
        output.push_str("    any of them\n");
    }
    output.push_str("}\n");

    Ok(output)
}

fn current_timestamp() -> String {
    match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(duration) => duration.as_secs().to_string(),
        Err(_) => "0".to_string(),
    }
}

fn sanitize_rule_name(binary_name: &str) -> String {
    let mut sanitized = String::new();
    for ch in binary_name.chars() {
        if ch.is_ascii_alphanumeric() {
            sanitized.push(ch);
        } else {
            sanitized.push('_');
        }
    }

    if sanitized.is_empty() {
        sanitized.push('_');
    }

    let first = sanitized.chars().next().unwrap_or('_');
    if !first.is_ascii_alphabetic() && first != '_' {
        sanitized.insert(0, '_');
    }

    sanitized
}

fn sanitize_identifier(name: &str) -> String {
    let mut sanitized = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            sanitized.push(ch);
        } else {
            sanitized.push('_');
        }
    }

    if sanitized.is_empty() {
        "tag".to_string()
    } else {
        sanitized
    }
}

fn escape_yara_string(text: &str) -> String {
    let mut escaped = String::new();
    for byte in text.as_bytes() {
        match *byte {
            b'\\' => escaped.push_str("\\\\"),
            b'"' => escaped.push_str("\\\""),
            b'\n' => escaped.push_str("\\n"),
            b'\r' => escaped.push_str("\\r"),
            b'\t' => escaped.push_str("\\t"),
            0x08 => escaped.push_str("\\b"),
            0x0b => escaped.push_str("\\x0b"),
            0x0c => escaped.push_str("\\x0c"),
            0x00..=0x1f | 0x7f..=0xff => {
                escaped.push_str(&format!("\\x{:02x}", byte));
            }
            _ => escaped.push(*byte as char),
        }
    }
    escaped
}

fn escape_yara_unicode_literal(text: &str) -> String {
    let mut escaped = String::new();
    for ch in text.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            _ if ch.is_control() => {
                let mut buf = [0; 4];
                let encoded = ch.encode_utf8(&mut buf);
                for byte in encoded.as_bytes() {
                    escaped.push_str(&format!("\\x{:02x}", byte));
                }
            }
            _ => escaped.push(ch),
        }
    }
    escaped
}

fn utf16be_hex_string(text: &str) -> String {
    let mut bytes = Vec::new();
    for unit in text.encode_utf16() {
        bytes.extend_from_slice(&unit.to_be_bytes());
    }

    if bytes.is_empty() {
        return "{ }".to_string();
    }

    let mut hex = String::new();
    hex.push_str("{ ");
    for (idx, byte) in bytes.iter().enumerate() {
        if idx > 0 {
            hex.push(' ');
        }
        hex.push_str(&format!("{:02x}", byte));
    }
    hex.push_str(" }");
    hex
}

fn get_yara_modifier(encoding: Encoding) -> &'static str {
    match encoding {
        Encoding::Ascii | Encoding::Utf8 => "ascii",
        Encoding::Utf16Le | Encoding::Utf16Be => "wide",
    }
}

fn tag_name(tag: &crate::types::Tag) -> &'static str {
    match tag {
        crate::types::Tag::Url => "Url",
        crate::types::Tag::Domain => "Domain",
        crate::types::Tag::IPv4 => "ipv4",
        crate::types::Tag::IPv6 => "ipv6",
        crate::types::Tag::FilePath => "filepath",
        crate::types::Tag::RegistryPath => "regpath",
        crate::types::Tag::Guid => "guid",
        crate::types::Tag::Email => "Email",
        crate::types::Tag::Base64 => "b64",
        crate::types::Tag::FormatString => "fmt",
        crate::types::Tag::UserAgent => "user-agent-ish",
        crate::types::Tag::DemangledSymbol => "demangled",
        crate::types::Tag::Import => "Import",
        crate::types::Tag::Export => "Export",
        crate::types::Tag::Version => "Version",
        crate::types::Tag::Manifest => "Manifest",
        crate::types::Tag::Resource => "Resource",
        crate::types::Tag::DylibPath => "dylib-path",
        crate::types::Tag::Rpath => "rpath",
        crate::types::Tag::RpathVariable => "rpath-var",
        crate::types::Tag::FrameworkPath => "framework-path",
    }
}

fn group_strings_by_tag(strings: &[FoundString]) -> BTreeMap<String, Vec<&FoundString>> {
    let mut grouped: BTreeMap<String, Vec<&FoundString>> = BTreeMap::new();

    for item in strings {
        let tag = item
            .tags
            .first()
            .map(|tag| tag_name(tag).to_string())
            .unwrap_or_else(|| "untagged".to_string());
        grouped.entry(tag).or_default().push(item);
    }

    grouped
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::output::{OutputFormat, OutputMetadata};
    use crate::types::{FoundString, StringSource, Tag};

    fn make_metadata() -> OutputMetadata {
        OutputMetadata::new("sample.bin".to_string(), OutputFormat::Yara, 0, 0)
    }

    fn make_string(text: &str) -> FoundString {
        FoundString::new(
            text.to_string(),
            Encoding::Ascii,
            0,
            text.len() as u32,
            StringSource::SectionData,
        )
    }

    #[test]
    fn test_sanitize_rule_name() {
        assert_eq!(sanitize_rule_name("sample.bin"), "sample_bin");
        assert_eq!(sanitize_rule_name("123name"), "_123name");
        assert_eq!(sanitize_rule_name("$weird#name"), "_weird_name");
        assert_eq!(sanitize_rule_name(""), "_");
    }

    #[test]
    fn test_escape_yara_string() {
        let input = "quote\" backslash\\ line\n tab\t";
        let escaped = escape_yara_string(input);
        assert!(escaped.contains("\\\""));
        assert!(escaped.contains("\\\\"));
        assert!(escaped.contains("\\n"));
        assert!(escaped.contains("\\t"));
    }

    #[test]
    fn test_get_yara_modifier() {
        assert_eq!(get_yara_modifier(Encoding::Ascii), "ascii");
        assert_eq!(get_yara_modifier(Encoding::Utf8), "ascii");
        assert_eq!(get_yara_modifier(Encoding::Utf16Le), "wide");
        assert_eq!(get_yara_modifier(Encoding::Utf16Be), "wide");
    }

    #[test]
    fn test_group_strings_by_tag() {
        let strings = vec![
            make_string("one").with_tags(vec![Tag::Url]),
            make_string("two").with_tags(vec![Tag::Domain]),
            make_string("three"),
        ];
        let grouped = group_strings_by_tag(&strings);
        assert!(grouped.contains_key("Url"));
        assert!(grouped.contains_key("Domain"));
        assert!(grouped.contains_key("untagged"));
    }

    #[test]
    fn test_empty_strings_produces_minimal_rule() {
        let output = format_yara(&[], &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("condition:"));
        assert!(output.contains("true"));
    }

    #[test]
    fn test_single_string_produces_rule() {
        let strings = vec![make_string("alpha").with_tags(vec![Tag::Url])];
        let output = format_yara(&strings, &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("strings:"));
        assert!(output.contains("$Url_1"));
        assert!(output.contains("\"alpha\""));
    }

    #[test]
    fn test_long_strings_are_skipped() {
        let long_text = "a".repeat(201);
        let strings = vec![make_string(&long_text).with_tags(vec![Tag::Url])];
        let output = format_yara(&strings, &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("skipped (length > 200 chars)"));
    }

    #[test]
    fn test_binary_name_sanitization_in_rule_name() {
        let metadata = OutputMetadata::new("weird name.exe".to_string(), OutputFormat::Yara, 1, 1);
        let strings = vec![make_string("alpha")];
        let output = format_yara(&strings, &metadata).expect("Formatting should succeed");
        assert!(output.contains("rule weird_name_exe_strings"));
    }

    #[test]
    fn test_encodings_apply_modifiers() {
        let mut string = make_string("wide");
        string.encoding = Encoding::Utf16Le;
        let output = format_yara(&[string], &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("wide"));
    }

    #[test]
    fn test_unicode_content_is_escaped() {
        let unicode = "\u{4E2D}\u{6587}";
        let strings = vec![make_string(unicode).with_tags(vec![Tag::Domain])];
        let output = format_yara(&strings, &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("\\x"));
    }
}
