use crate::types::{Encoding, FoundString, Result, Tag};

use super::OutputMetadata;
use std::collections::{BTreeMap, HashMap};
use std::time::{SystemTime, UNIX_EPOCH};

/// Format strings as YARA rule templates.
pub fn format_yara(strings: &[FoundString], metadata: &OutputMetadata) -> Result<String> {
    let timestamp = metadata
        .generated_at
        .clone()
        .unwrap_or_else(current_timestamp);
    let base_rule_name = sanitize_rule_name(&metadata.binary_name);
    let rule_name = format!("{}_strings", base_rule_name);

    let mut output = String::new();
    output.push_str("// YARA rule generated by Stringy\n");
    output.push_str(&format!(
        "// Binary: {}\n",
        escape_yara_string(&metadata.binary_name)
    ));
    output.push_str(&format!(
        "// Generated: {}\n\n",
        escape_yara_string(&timestamp)
    ));

    output.push_str(&format!("rule {} {{\n", rule_name));
    output.push_str("  meta:\n");
    output.push_str(&format!(
        "    description = \"Strings extracted from {}\"\n",
        escape_yara_string(&metadata.binary_name)
    ));
    output.push_str("    generated_by = \"stringy\"\n");
    output.push_str(&format!(
        "    generated_at = \"{}\"\n",
        escape_yara_string(&timestamp)
    ));

    if strings.is_empty() {
        output.push_str("  condition:\n");
        output.push_str("    true\n");
        output.push_str("}\n");
        return Ok(output);
    }

    let grouped = group_strings_by_tag(strings);
    let mut strings_block = String::new();
    let mut counters: HashMap<String, usize> = HashMap::new();
    let mut included = 0usize;

    strings_block.push_str("  strings:\n");
    for (tag, items) in grouped {
        strings_block.push_str(&format!("    // tag: {}\n", tag));
        let var_tag = sanitize_identifier(&tag);
        for item in items {
            let char_count = item.text.chars().count();
            if char_count > 200 {
                strings_block.push_str(&format!(
                    "    // skipped (length > 200 chars): {}\n",
                    char_count
                ));
                continue;
            }

            let counter = counters.entry(var_tag.clone()).or_insert(0);
            *counter += 1;
            let var_name = format!("${}_{}", var_tag, *counter);
            strings_block.push_str(&format!("    // score: {}\n", item.score));

            match item.encoding {
                Encoding::Utf16Be => {
                    let hex = utf16be_hex_string(&item.text);
                    strings_block.push_str(&format!("    {} = {}\n", var_name, hex));
                }
                Encoding::Utf16Le => {
                    if item.text.is_ascii() {
                        let escaped = escape_yara_unicode_literal(&item.text);
                        strings_block
                            .push_str(&format!("    {} = \"{}\" wide\n", var_name, escaped));
                    } else {
                        let hex = utf16le_hex_string(&item.text);
                        strings_block.push_str(&format!("    {} = {}\n", var_name, hex));
                    }
                }
                Encoding::Ascii | Encoding::Utf8 => {
                    let escaped = escape_yara_string(&item.text);
                    strings_block.push_str(&format!("    {} = \"{}\" ascii\n", var_name, escaped));
                }
            }
            included += 1;
        }
    }

    output.push_str(&strings_block);
    output.push_str("  condition:\n");
    if included == 0 {
        output.push_str("    true\n");
    } else {
        output.push_str("    any of them\n");
    }
    output.push_str("}\n");

    Ok(output)
}

fn current_timestamp() -> String {
    match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(duration) => duration.as_secs().to_string(),
        // Return a clearly invalid timestamp if system clock is before Unix epoch.
        // This avoids silently producing "0" which looks like a valid epoch timestamp.
        Err(_) => "CLOCK_ERROR".to_string(),
    }
}

fn sanitize_rule_name(binary_name: &str) -> String {
    let mut sanitized = String::new();
    for ch in binary_name.chars() {
        if ch.is_ascii_alphanumeric() {
            sanitized.push(ch);
        } else {
            sanitized.push('_');
        }
    }

    if sanitized.is_empty() {
        sanitized.push('_');
    }

    let first = sanitized.chars().next().unwrap_or('_');
    if !first.is_ascii_alphabetic() && first != '_' {
        sanitized.insert(0, '_');
    }

    sanitized
}

fn sanitize_identifier(name: &str) -> String {
    let mut sanitized = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            sanitized.push(ch);
        } else {
            sanitized.push('_');
        }
    }

    if sanitized.is_empty() {
        "tag".to_string()
    } else {
        sanitized
    }
}

fn escape_yara_string(text: &str) -> String {
    let mut escaped = String::new();
    for byte in text.as_bytes() {
        match *byte {
            b'\\' => escaped.push_str("\\\\"),
            b'"' => escaped.push_str("\\\""),
            b'\n' => escaped.push_str("\\n"),
            b'\r' => escaped.push_str("\\r"),
            b'\t' => escaped.push_str("\\t"),
            0x08 => escaped.push_str("\\b"),
            0x0b => escaped.push_str("\\x0b"),
            0x0c => escaped.push_str("\\x0c"),
            0x00..=0x1f | 0x7f..=0xff => {
                escaped.push_str(&format!("\\x{:02x}", byte));
            }
            _ => escaped.push(*byte as char),
        }
    }
    escaped
}

fn escape_yara_unicode_literal(text: &str) -> String {
    let mut escaped = String::new();
    for ch in text.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            _ if ch.is_control() => {
                let mut buf = [0; 4];
                let encoded = ch.encode_utf8(&mut buf);
                for byte in encoded.as_bytes() {
                    escaped.push_str(&format!("\\x{:02x}", byte));
                }
            }
            _ => escaped.push(ch),
        }
    }
    escaped
}

fn utf16be_hex_string(text: &str) -> String {
    let hex_bytes: Vec<String> = text
        .encode_utf16()
        .flat_map(|unit| unit.to_be_bytes())
        .map(|b| format!("{:02x}", b))
        .collect();

    if hex_bytes.is_empty() {
        return "{ }".to_string();
    }

    format!("{{ {} }}", hex_bytes.join(" "))
}

fn utf16le_hex_string(text: &str) -> String {
    let hex_bytes: Vec<String> = text
        .encode_utf16()
        .flat_map(|unit| unit.to_le_bytes())
        .map(|b| format!("{:02x}", b))
        .collect();

    if hex_bytes.is_empty() {
        return "{ }".to_string();
    }

    format!("{{ {} }}", hex_bytes.join(" "))
}

fn tag_name(tag: &Tag) -> &'static str {
    match tag {
        Tag::Url => "Url",
        Tag::Domain => "Domain",
        Tag::IPv4 => "ipv4",
        Tag::IPv6 => "ipv6",
        Tag::FilePath => "filepath",
        Tag::RegistryPath => "regpath",
        Tag::Guid => "guid",
        Tag::Email => "Email",
        Tag::Base64 => "b64",
        Tag::FormatString => "fmt",
        Tag::UserAgent => "user-agent-ish",
        Tag::DemangledSymbol => "demangled",
        Tag::Import => "Import",
        Tag::Export => "Export",
        Tag::Version => "Version",
        Tag::Manifest => "Manifest",
        Tag::Resource => "Resource",
        Tag::DylibPath => "dylib-path",
        Tag::Rpath => "rpath",
        Tag::RpathVariable => "rpath-var",
        Tag::FrameworkPath => "framework-path",
    }
}

fn group_strings_by_tag(strings: &[FoundString]) -> BTreeMap<String, Vec<&FoundString>> {
    let mut grouped: BTreeMap<String, Vec<&FoundString>> = BTreeMap::new();

    for item in strings {
        let tag = item
            .tags
            .first()
            .map(|tag| tag_name(tag).to_string())
            .unwrap_or_else(|| "untagged".to_string());
        grouped.entry(tag).or_default().push(item);
    }

    grouped
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::output::{OutputFormat, OutputMetadata};
    use crate::types::{FoundString, StringSource, Tag};

    fn make_metadata() -> OutputMetadata {
        OutputMetadata::new("sample.bin".to_string(), OutputFormat::Yara, 0, 0)
    }

    fn make_string(text: &str) -> FoundString {
        FoundString::new(
            text.to_string(),
            Encoding::Ascii,
            0,
            text.len() as u32,
            StringSource::SectionData,
        )
    }

    #[test]
    fn test_sanitize_rule_name() {
        assert_eq!(sanitize_rule_name("sample.bin"), "sample_bin");
        assert_eq!(sanitize_rule_name("123name"), "_123name");
        assert_eq!(sanitize_rule_name("$weird#name"), "_weird_name");
        assert_eq!(sanitize_rule_name(""), "_");
    }

    #[test]
    fn test_escape_yara_string() {
        let input = "quote\" backslash\\ line\n tab\t";
        let escaped = escape_yara_string(input);
        assert!(escaped.contains("\\\""));
        assert!(escaped.contains("\\\\"));
        assert!(escaped.contains("\\n"));
        assert!(escaped.contains("\\t"));
    }

    #[test]
    fn test_group_strings_by_tag() {
        let strings = vec![
            make_string("one").with_tags(vec![Tag::Url]),
            make_string("two").with_tags(vec![Tag::Domain]),
            make_string("three"),
        ];
        let grouped = group_strings_by_tag(&strings);
        assert!(grouped.contains_key("Url"));
        assert!(grouped.contains_key("Domain"));
        assert!(grouped.contains_key("untagged"));
    }

    #[test]
    fn test_empty_strings_produces_minimal_rule() {
        let output = format_yara(&[], &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("condition:"));
        assert!(output.contains("true"));
    }

    #[test]
    fn test_single_string_produces_rule() {
        let strings = vec![make_string("alpha").with_tags(vec![Tag::Url])];
        let output = format_yara(&strings, &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("strings:"));
        assert!(output.contains("$Url_1"));
        assert!(output.contains("\"alpha\""));
    }

    #[test]
    fn test_long_strings_are_skipped() {
        let long_text = "a".repeat(201);
        let strings = vec![make_string(&long_text).with_tags(vec![Tag::Url])];
        let output = format_yara(&strings, &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("skipped (length > 200 chars)"));
    }

    #[test]
    fn test_binary_name_sanitization_in_rule_name() {
        let metadata = OutputMetadata::new("weird name.exe".to_string(), OutputFormat::Yara, 1, 1);
        let strings = vec![make_string("alpha")];
        let output = format_yara(&strings, &metadata).expect("Formatting should succeed");
        assert!(output.contains("rule weird_name_exe_strings"));
    }

    #[test]
    fn test_encodings_apply_modifiers() {
        let mut string = make_string("wide");
        string.encoding = Encoding::Utf16Le;
        let output = format_yara(&[string], &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("wide"));
    }

    #[test]
    fn test_unicode_content_is_escaped() {
        let unicode = "\u{4E2D}\u{6587}";
        let strings = vec![make_string(unicode).with_tags(vec![Tag::Domain])];
        let output = format_yara(&strings, &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("\\x"));
    }

    #[test]
    fn test_escape_yara_unicode_literal_basic() {
        // Basic escapes
        assert_eq!(escape_yara_unicode_literal("quote\""), "quote\\\"");
        assert_eq!(escape_yara_unicode_literal("back\\slash"), "back\\\\slash");
        assert_eq!(escape_yara_unicode_literal("line\nbreak"), "line\\nbreak");
        assert_eq!(escape_yara_unicode_literal("tab\there"), "tab\\there");
        assert_eq!(escape_yara_unicode_literal("return\rhere"), "return\\rhere");
    }

    #[test]
    fn test_escape_yara_unicode_literal_control_chars() {
        // Control characters should be hex-escaped
        assert_eq!(escape_yara_unicode_literal("\x00"), "\\x00");
        assert_eq!(escape_yara_unicode_literal("\x1f"), "\\x1f");
    }

    #[test]
    fn test_escape_yara_unicode_literal_unicode_passthrough() {
        // Non-control Unicode should pass through unescaped
        let result = escape_yara_unicode_literal("\u{4E2D}\u{6587}");
        assert!(
            result.contains('\u{4E2D}'),
            "Non-control Unicode should not be escaped"
        );
    }

    #[test]
    fn test_escape_yara_unicode_literal_empty() {
        assert_eq!(escape_yara_unicode_literal(""), "");
    }

    #[test]
    fn test_utf16be_hex_string_basic() {
        // Basic ASCII - should be big-endian (00 followed by ASCII byte)
        assert_eq!(utf16be_hex_string("A"), "{ 00 41 }");
        assert_eq!(utf16be_hex_string("AB"), "{ 00 41 00 42 }");
    }

    #[test]
    fn test_utf16be_hex_string_empty() {
        assert_eq!(utf16be_hex_string(""), "{ }");
    }

    #[test]
    fn test_utf16be_hex_string_non_ascii() {
        // Non-ASCII Unicode (BMP) - Chinese character U+4E2D
        let chinese = utf16be_hex_string("\u{4E2D}");
        assert_eq!(chinese, "{ 4e 2d }");
    }

    #[test]
    fn test_utf16be_hex_string_surrogate_pair() {
        // Character requiring surrogate pair (outside BMP) - emoji U+1F600
        let emoji = utf16be_hex_string("\u{1F600}");
        // Should produce surrogate pair: D83D DE00
        assert_eq!(emoji, "{ d8 3d de 00 }");
    }

    #[test]
    fn test_escape_yara_string_control_characters() {
        assert_eq!(escape_yara_string("\r"), "\\r");
        assert_eq!(escape_yara_string("\x00"), "\\x00");
        assert_eq!(escape_yara_string("\x08"), "\\b");
        assert_eq!(escape_yara_string("\x0b"), "\\x0b");
        assert_eq!(escape_yara_string("\x0c"), "\\x0c");
        assert_eq!(escape_yara_string("\x7f"), "\\x7f");
    }

    #[test]
    fn test_format_yara_uses_current_timestamp_when_not_set() {
        // When generated_at is None, format_yara should use current_timestamp()
        let metadata = OutputMetadata::new("test.bin".to_string(), OutputFormat::Yara, 0, 0);
        // Note: generated_at is None
        let output = format_yara(&[], &metadata).expect("Formatting should succeed");

        // Should contain a timestamp in the generated_at field
        assert!(output.contains("generated_at = \""));
        // Timestamp should be numeric (or CLOCK_ERROR in exceptional cases)
        assert!(
            output.contains("generated_at = \"1")
                || output.contains("generated_at = \"CLOCK_ERROR"),
            "Timestamp should be numeric or CLOCK_ERROR"
        );
    }

    #[test]
    fn test_utf16le_hex_string_basic() {
        // Basic ASCII - should be little-endian (ASCII byte followed by 00)
        assert_eq!(utf16le_hex_string("A"), "{ 41 00 }");
        assert_eq!(utf16le_hex_string("AB"), "{ 41 00 42 00 }");
    }

    #[test]
    fn test_utf16le_hex_string_empty() {
        assert_eq!(utf16le_hex_string(""), "{ }");
    }

    #[test]
    fn test_utf16le_hex_string_non_ascii() {
        // Non-ASCII Unicode (BMP) - Chinese character U+4E2D
        let chinese = utf16le_hex_string("\u{4E2D}");
        assert_eq!(chinese, "{ 2d 4e }");
    }

    #[test]
    fn test_utf16le_hex_string_surrogate_pair() {
        // Character requiring surrogate pair (outside BMP) - emoji U+1F600
        let emoji = utf16le_hex_string("\u{1F600}");
        // Should produce surrogate pair: 3D D8 00 DE (little-endian)
        assert_eq!(emoji, "{ 3d d8 00 de }");
    }

    #[test]
    fn test_utf16le_ascii_uses_wide_modifier() {
        // ASCII UTF-16LE should use "wide" modifier
        let mut string = make_string("test");
        string.encoding = Encoding::Utf16Le;
        let output = format_yara(&[string], &make_metadata()).expect("Formatting should succeed");
        assert!(
            output.contains("wide"),
            "ASCII UTF-16LE should use wide modifier"
        );
        assert!(output.contains("\"test\""));
    }

    #[test]
    fn test_utf16le_non_ascii_uses_hex() {
        // Non-ASCII UTF-16LE should use hex string, not wide modifier
        let mut string = make_string("\u{4E2D}\u{6587}");
        string.encoding = Encoding::Utf16Le;
        let output = format_yara(&[string], &make_metadata()).expect("Formatting should succeed");
        assert!(
            !output.contains("wide"),
            "Non-ASCII UTF-16LE should not use wide modifier"
        );
        assert!(
            output.contains("{ 2d 4e 87 65 }"),
            "Non-ASCII UTF-16LE should use hex encoding"
        );
    }

    #[test]
    fn test_binary_name_injection_escaped_in_comments() {
        // Binary name with newlines should be escaped in comments
        let mut metadata = make_metadata();
        metadata.binary_name = "evil\nname".to_string();
        let output = format_yara(&[], &metadata).expect("Formatting should succeed");
        // Should contain escaped newline, not literal
        assert!(
            output.contains("evil\\nname"),
            "Newlines in binary_name should be escaped"
        );
        assert!(
            !output.contains("evil\nname"),
            "Literal newlines should not appear"
        );
    }

    #[test]
    fn test_timestamp_injection_escaped_in_meta() {
        // Timestamp with special characters should be escaped
        let mut metadata = make_metadata();
        metadata.generated_at = Some("2024\"\n//attack".to_string());
        let output = format_yara(&[], &metadata).expect("Formatting should succeed");
        // Should contain escaped characters
        assert!(
            output.contains("2024\\\"\\n//attack"),
            "Special chars in timestamp should be escaped"
        );
    }
}
