//! YARA rule generation from extracted strings.
//!
//! Generates YARA rule templates suitable for malware analysis and detection.
//! Strings are grouped by tag and formatted with appropriate encoding modifiers.

mod escaping;

use crate::types::{Encoding, FoundString, Result, Tag};
use escaping::{
    escape_yara_string, escape_yara_unicode_literal, utf16be_hex_string, utf16le_hex_string,
};

use super::OutputMetadata;
use std::collections::{BTreeMap, HashMap};
use std::time::{SystemTime, UNIX_EPOCH};

/// Format strings as YARA rule templates.
pub fn format_yara(strings: &[FoundString], metadata: &OutputMetadata) -> Result<String> {
    let timestamp = metadata
        .generated_at
        .clone()
        .unwrap_or_else(current_timestamp);
    let base_rule_name = sanitize_rule_name(&metadata.binary_name);
    let rule_name = format!("{}_strings", base_rule_name);

    let mut output = String::new();
    output.push_str("// YARA rule generated by Stringy\n");
    output.push_str(&format!(
        "// Binary: {}\n",
        escape_yara_string(&metadata.binary_name)
    ));
    output.push_str(&format!(
        "// Generated: {}\n\n",
        escape_yara_string(&timestamp)
    ));

    output.push_str(&format!("rule {} {{\n", rule_name));
    output.push_str("  meta:\n");
    output.push_str(&format!(
        "    description = \"Strings extracted from {}\"\n",
        escape_yara_string(&metadata.binary_name)
    ));
    output.push_str("    generated_by = \"stringy\"\n");
    output.push_str(&format!(
        "    generated_at = \"{}\"\n",
        escape_yara_string(&timestamp)
    ));

    if strings.is_empty() {
        output.push_str("  condition:\n");
        output.push_str("    true\n");
        output.push_str("}\n");
        return Ok(output);
    }

    let grouped = group_strings_by_tag(strings);
    let mut strings_block = String::new();
    let mut counters: HashMap<String, usize> = HashMap::new();
    let mut included = 0usize;

    strings_block.push_str("  strings:\n");
    for (tag, items) in grouped {
        strings_block.push_str(&format!("    // tag: {}\n", tag));
        let var_tag = sanitize_identifier(&tag);
        for item in items {
            let char_count = item.text.chars().count();
            if char_count > 200 {
                strings_block.push_str(&format!(
                    "    // skipped (length > 200 chars): {}\n",
                    char_count
                ));
                continue;
            }

            let counter = counters.entry(var_tag.clone()).or_insert(0);
            *counter += 1;
            let var_name = format!("${}_{}", var_tag, *counter);
            strings_block.push_str(&format!("    // score: {}\n", item.score));

            match item.encoding {
                Encoding::Utf16Be => {
                    let hex = utf16be_hex_string(&item.text);
                    strings_block.push_str(&format!("    {} = {}\n", var_name, hex));
                }
                Encoding::Utf16Le => {
                    if item.text.is_ascii() {
                        let escaped = escape_yara_unicode_literal(&item.text);
                        strings_block
                            .push_str(&format!("    {} = \"{}\" wide\n", var_name, escaped));
                    } else {
                        let hex = utf16le_hex_string(&item.text);
                        strings_block.push_str(&format!("    {} = {}\n", var_name, hex));
                    }
                }
                Encoding::Ascii | Encoding::Utf8 => {
                    let escaped = escape_yara_string(&item.text);
                    strings_block.push_str(&format!("    {} = \"{}\" ascii\n", var_name, escaped));
                }
            }
            included += 1;
        }
    }

    output.push_str(&strings_block);
    output.push_str("  condition:\n");
    if included == 0 {
        output.push_str("    true\n");
    } else {
        output.push_str("    any of them\n");
    }
    output.push_str("}\n");

    Ok(output)
}

fn current_timestamp() -> String {
    match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(duration) => duration.as_secs().to_string(),
        // Return a clearly invalid timestamp if system clock is before Unix epoch.
        // This avoids silently producing "0" which looks like a valid epoch timestamp.
        Err(_) => "CLOCK_ERROR".to_string(),
    }
}

fn sanitize_rule_name(binary_name: &str) -> String {
    let mut sanitized = String::new();
    for ch in binary_name.chars() {
        if ch.is_ascii_alphanumeric() {
            sanitized.push(ch);
        } else {
            sanitized.push('_');
        }
    }

    if sanitized.is_empty() {
        sanitized.push('_');
    }

    let first = sanitized.chars().next().unwrap_or('_');
    if !first.is_ascii_alphabetic() && first != '_' {
        sanitized.insert(0, '_');
    }

    sanitized
}

fn sanitize_identifier(name: &str) -> String {
    let mut sanitized = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            sanitized.push(ch);
        } else {
            sanitized.push('_');
        }
    }

    if sanitized.is_empty() {
        "tag".to_string()
    } else {
        sanitized
    }
}

fn tag_name(tag: &Tag) -> &'static str {
    match tag {
        Tag::Url => "Url",
        Tag::Domain => "Domain",
        Tag::IPv4 => "ipv4",
        Tag::IPv6 => "ipv6",
        Tag::FilePath => "filepath",
        Tag::RegistryPath => "regpath",
        Tag::Guid => "guid",
        Tag::Email => "Email",
        Tag::Base64 => "b64",
        Tag::FormatString => "fmt",
        Tag::UserAgent => "user-agent-ish",
        Tag::DemangledSymbol => "demangled",
        Tag::Import => "Import",
        Tag::Export => "Export",
        Tag::Version => "Version",
        Tag::Manifest => "Manifest",
        Tag::Resource => "Resource",
        Tag::DylibPath => "dylib-path",
        Tag::Rpath => "rpath",
        Tag::RpathVariable => "rpath-var",
        Tag::FrameworkPath => "framework-path",
    }
}

fn group_strings_by_tag(strings: &[FoundString]) -> BTreeMap<String, Vec<&FoundString>> {
    let mut grouped: BTreeMap<String, Vec<&FoundString>> = BTreeMap::new();

    for item in strings {
        let tag = item
            .tags
            .first()
            .map(|tag| tag_name(tag).to_string())
            .unwrap_or_else(|| "untagged".to_string());
        grouped.entry(tag).or_default().push(item);
    }

    grouped
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::output::{OutputFormat, OutputMetadata};
    use crate::types::{FoundString, StringSource, Tag};

    fn make_metadata() -> OutputMetadata {
        OutputMetadata::new("sample.bin".to_string(), OutputFormat::Yara, 0, 0)
    }

    fn make_string(text: &str) -> FoundString {
        FoundString::new(
            text.to_string(),
            Encoding::Ascii,
            0,
            text.len() as u32,
            StringSource::SectionData,
        )
    }

    #[test]
    fn test_sanitize_rule_name() {
        assert_eq!(sanitize_rule_name("sample.bin"), "sample_bin");
        assert_eq!(sanitize_rule_name("123name"), "_123name");
        assert_eq!(sanitize_rule_name("$weird#name"), "_weird_name");
        assert_eq!(sanitize_rule_name(""), "_");
    }

    #[test]
    fn test_group_strings_by_tag() {
        let strings = vec![
            make_string("one").with_tags(vec![Tag::Url]),
            make_string("two").with_tags(vec![Tag::Domain]),
            make_string("three"),
        ];
        let grouped = group_strings_by_tag(&strings);
        assert!(grouped.contains_key("Url"));
        assert!(grouped.contains_key("Domain"));
        assert!(grouped.contains_key("untagged"));
    }

    #[test]
    fn test_empty_strings_produces_minimal_rule() {
        let output = format_yara(&[], &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("condition:"));
        assert!(output.contains("true"));
    }

    #[test]
    fn test_single_string_produces_rule() {
        let strings = vec![make_string("alpha").with_tags(vec![Tag::Url])];
        let output = format_yara(&strings, &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("strings:"));
        assert!(output.contains("$Url_1"));
        assert!(output.contains("\"alpha\""));
    }

    #[test]
    fn test_long_strings_are_skipped() {
        let long_text = "a".repeat(201);
        let strings = vec![make_string(&long_text).with_tags(vec![Tag::Url])];
        let output = format_yara(&strings, &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("skipped (length > 200 chars)"));
    }

    #[test]
    fn test_binary_name_sanitization_in_rule_name() {
        let metadata = OutputMetadata::new("weird name.exe".to_string(), OutputFormat::Yara, 1, 1);
        let strings = vec![make_string("alpha")];
        let output = format_yara(&strings, &metadata).expect("Formatting should succeed");
        assert!(output.contains("rule weird_name_exe_strings"));
    }

    #[test]
    fn test_encodings_apply_modifiers() {
        let mut string = make_string("wide");
        string.encoding = Encoding::Utf16Le;
        let output = format_yara(&[string], &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("wide"));
    }

    #[test]
    fn test_unicode_content_is_escaped() {
        let unicode = "\u{4E2D}\u{6587}";
        let strings = vec![make_string(unicode).with_tags(vec![Tag::Domain])];
        let output = format_yara(&strings, &make_metadata()).expect("Formatting should succeed");
        assert!(output.contains("\\x"));
    }

    #[test]
    fn test_format_yara_uses_current_timestamp_when_not_set() {
        let metadata = OutputMetadata::new("test.bin".to_string(), OutputFormat::Yara, 0, 0);
        let output = format_yara(&[], &metadata).expect("Formatting should succeed");

        assert!(output.contains("generated_at = \""));
        assert!(
            output.contains("generated_at = \"1")
                || output.contains("generated_at = \"CLOCK_ERROR"),
            "Timestamp should be numeric or CLOCK_ERROR"
        );
    }

    #[test]
    fn test_utf16le_ascii_uses_wide_modifier() {
        let mut string = make_string("test");
        string.encoding = Encoding::Utf16Le;
        let output = format_yara(&[string], &make_metadata()).expect("Formatting should succeed");
        assert!(
            output.contains("wide"),
            "ASCII UTF-16LE should use wide modifier"
        );
        assert!(output.contains("\"test\""));
    }

    #[test]
    fn test_utf16le_non_ascii_uses_hex() {
        let mut string = make_string("\u{4E2D}\u{6587}");
        string.encoding = Encoding::Utf16Le;
        let output = format_yara(&[string], &make_metadata()).expect("Formatting should succeed");
        assert!(
            !output.contains("wide"),
            "Non-ASCII UTF-16LE should not use wide modifier"
        );
        assert!(
            output.contains("{ 2d 4e 87 65 }"),
            "Non-ASCII UTF-16LE should use hex encoding"
        );
    }

    #[test]
    fn test_binary_name_injection_escaped_in_comments() {
        let mut metadata = make_metadata();
        metadata.binary_name = "evil\nname".to_string();
        let output = format_yara(&[], &metadata).expect("Formatting should succeed");
        assert!(
            output.contains("evil\\nname"),
            "Newlines in binary_name should be escaped"
        );
        assert!(
            !output.contains("evil\nname"),
            "Literal newlines should not appear"
        );
    }

    #[test]
    fn test_timestamp_injection_escaped_in_meta() {
        let mut metadata = make_metadata();
        metadata.generated_at = Some("2024\"\n//attack".to_string());
        let output = format_yara(&[], &metadata).expect("Formatting should succeed");
        assert!(
            output.contains("2024\\\"\\n//attack"),
            "Special chars in timestamp should be escaped"
        );
    }
}
