[book]
authors = ["UncleSp1d3r <unclesp1d3r@evilbitlabs.io>"]
language = "en"
multilingual = false
src = "src"
title = "Stringy Developer Guide"
description = "Developer documentation for Stringy - A smarter strings extraction tool"

[preprocessor.links]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/EvilBit-Labs/string_mcstringface"
edit-url-template = "https://github.com/EvilBit-Labs/string_mcstringface/edit/main/docs/{path}"

[output.html.playground]
editable = false
copyable = true
copy-js = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
